
stages:
  - build

before_script:
  - echo "--------- STARTING WORK ------------"
  - sh script.sh 
variables:
  SCRIPT: $(./script.sh) 
package the maven project:
  stage: build
  script: 
  - mvn clean package 
  - sed -i "s/VERSION/$SCRIPT/" ./pom.xml
  tags:
    - george
  allow_failure: false
  artifacts:
    paths:
      - target/*.jar 

