
stages:
  - build
  - docker

before_script:
  - echo "--------- STARTING WORK ------------"
  - sh script.sh 
variables:
  docker_user: georgemusa
  docker_pass: Y2b;!@g/m;Q6s)$

#-----------------------------------------------# 
package the maven project:
  stage: build
  script:
  - version=`sh script.sh` 
  - sed -i "s/%%VERSION%%/"$version"/" pom.xml 
  - mvn versions:set -DnewVersion=$version
  - mvn clean package 
  tags:
    - george  
  allow_failure: false
  artifacts:
    paths:
      - target/*.jar 
#-----------------------------------------------# 
build the docker image:
  stage: docker
  script:
    - version=`sh script.sh`
    - docker build -t georgemusa/assignment:$version .
    - echo "$docker_pass" | docker login -u "$docker_user" --password-stdin
    - docker push georgemusa/assignment:$version
  tags:
    - george 
  artifacts:  
    paths:
      - target/*.jar 
#-----------------------------------------------#