
stages:
  - build

before_script:
  - echo "--------- STARTING WORK ------------"
  - sh script.sh 

package the maven project:
  stage: build
  script:
  - version=$(./script.sh)  
  - sed -i 's/%%VERSION%%/$version' pom.xml 
  - mvn clean package 
  tags:
    - george
  allow_failure: false
  artifacts:
    paths:
      - target/*.jar 

