stages:
  - build
  - docker
  - deploy
  - cleanup

before_script:
  - echo "--------- STARTING WORK ------------"
  - sh script.sh 
#-----------------------------------------------# 
package the maven project:
  stage: build
  script:
  - version=`sh script.sh` 
  - sed -i "s/%%VERSION%%/"$version"/" pom.xml 
  - mvn versions:set -DnewVersion=$version
  - mvn clean package 
  tags:
    - georgevm 
  allow_failure: false
  artifacts:
    paths:
      - target/*.jar 
#-----------------------------------------------# 
build the docker image:
  stage: docker
  script:
    - version=`sh script.sh`
    - docker build -t georgemusa/assignment:$version .
    - echo "$docker_pass" | docker login -u "$docker_user" --password-stdin
    - docker push georgemusa/assignment:$version
  tags:
    - georgevm
  artifacts:  
    paths:
      - target/*.jar 
#-----------------------------------------------#
deploy the manifest files:
 stage: deploy
 script:
   - version=`sh script.sh` 
   - kubectl create namespace 20210626-5cb745ed 
   - kubectl apply -f kub --namespace 20210626-5cb745ed 
 tags:
  - georgevm
#-----------------------------------------------#
cleanup:
  stage: cleanup
  tags:
    - georgevm
  when: manual
  script: 
    - version=`sh script.sh` 
    - kubectl delete namespace $version
#test
