
stages:
  - build

before_script:
  - sh script.sh
variables:
  SCRIPT: sh script.sh
package the maven project:
  stage: build
  script: 
  - mvn clean package 
  - sed -i "s/%%VERSION%%/$SCRIPT" ./devops_sample/pom.xml
  tags:
    - george
  allow_failure: false
  artifacts:
    paths:
      - target/*.jar 

