version: '3.7'

services: 
    database:
        container_name: mysql 
        image: mysql:latest
        restart: always
        ports: 
            - '3306:3306'
        environment: 
            MYSQL_DATABASE: 'assignment'
            MYSQL_USER: root
            MYSQL_PASSWORD: P@ssw0rd

    spring: 
        image: georgemusa/assignment:20210616-2b89db06
        container_name: spring_application
        restart: always
        ports: 
            - '8080:8080'
        depends_on: 
            - database
        environment:
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_USERNAME: P@ssw0rd
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/assignment?allowPublicKeyRetrieval=true



