version: '3'

services: 
    database:
        container_name: mysql
        image: mysql:8.0.19
        restart: always
        ports: 
            - 3306:3306
        environment: 
            MYSQL_DATABASE: assignment
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: P@ssw0rd

    spring: 
        image: georgemusa/assignment:20210815-b2f25830
        container_name: spring_application
        restart: always
        ports: 
            - 8090:8090
        depends_on: 
            - database
        environment:
            SPRING_PROFILE: mysql
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: P@ssw0rd
            SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/assignment?allowPublicKeyRetrieval=true