apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mysql
  name: {{ .Release.Name }}-mysql
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mysql
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mysql
    spec:
      containers:
      - image: {{ default "mysql:8.0.19" .Values.image.repository }}:{{ .Values.image.tag }}
        name: mysql
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        env: 
        - name: MYSQL_DATABASE 
          value: assignment
        - name: MYSQL_ROOT_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: MYSQL_ROOT_USER
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secret
              key: MYSQL_ROOT_PASSWORD
        resources: 
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}

status: {}
