apiVersion: v1
kind: Service
metadata:
  name: spring-srv
spec:
  type: LoadBalancer
  selector:
    app: spring-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  
  