apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  namespace: app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: devopspractice.com
      http:
        paths:
        - path: /?(.*)
          backend:
            serviceName: spring-srv
            servicePort: 8090
           
         
