apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: devopspractice.com
      http:
        paths:
        - path: /?(.*)
          pathType: Prefix
          backend:
            service: 
              name: spring-srv
              port: 
                number: 8090

# kubectl port-forward -n app spring-app-6b49bf4494-8hd8g 8090          
#networking.k8s.io/v1