apiVersion: v1
data:
  checkdatabase.sh: |-
    #!/bin/sh
    echo -e "Checking for the availability of MySQL Server deployment";  while ! nc -z mysql 3306; do sleep 1; printf "-"; done;  echo -e "  >> MySQL DB Server has started";
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: check-db
