apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: app-dep
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: app-dep
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
